name: Render README

on:
  push:
    paths:
      - 'README.Rmd'

jobs:
  render-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v1

      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("rstudio/rmarkdown")

      - name: Render README.Rmd
        run: Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: Commit rendered README.md
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md
          git commit -m "Render README.Rmd" || echo "No changes to commit"
          git push
