name: Test Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: r-lib/actions/setup-r@v1

    - name: Install dependencies
      run: |
        install.packages(c('covr', 'remotes'))
        remotes::install_deps(dependencies = TRUE)
      shell: Rscript {0}

    - name: Run tests and collect coverage
      run: |
        covr::codecov()
      shell: Rscript {0}
